# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('hp', models.PositiveSmallIntegerField()),
                ('poketype', models.CharField(max_length=250)),
                ('atk1name', models.CharField(max_length=250)),
                ('atk1power', models.PositiveSmallIntegerField()),
                ('atk2name', models.CharField(max_length=250, null=True)),
                ('atk2power', models.PositiveSmallIntegerField(null=True)),
                ('atk3name', models.CharField(max_length=250, null=True)),
                ('atk3power', models.PositiveSmallIntegerField(null=True)),
                ('atk4name', models.CharField(max_length=250, null=True)),
                ('atk4power', models.PositiveSmallIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('lvl', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poke.Pokemon')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon2', to='poke.Pokemon')),
                ('p3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pokemon3', to='poke.Pokemon')),
            ],
        ),
    ]
