# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_auto_20160725_2056'),
        ('poke', '0002_auto_20160725_1510'),
    ]

    operations = [
    ]
