# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 01:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_merge'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pokemon',
            managers=[
                ('pokemonManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
