# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_auto_20160726_2150'),
        ('poke', '0004_auto_20160725_1829'),
    ]

    operations = [
    ]
