# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0007_auto_20160728_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lose',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='win',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
