# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0008_auto_20160728_2347'),
        ('poke', '0008_auto_20160728_1733'),
    ]

    operations = [
    ]
